### ISSUE TITLE
下载好慢

### ISSUE THREAD

**Issue by mingkin** [ymcui/Chinese-BERT-wwm#100]
![image](https://user-images.githubusercontent.com/18612620/78424855-badc4a00-76a2-11ea-8e9d-2dcff2f9b3f9.png)

**Comment by ymcui** [comment]
也可以从google drive进行下载。具体原因暂不明。

**Comment by ymcui** [comment]
<img width="343" alt="image" src="https://user-images.githubusercontent.com/16095339/78425189-ce3ce480-76a5-11ea-8caf-59f5d0d618cd.png">
经测试网盘并没有什么问题。如果你那边下载慢的话，可以换个网络或者从google drive下载。
