### ISSUE TITLE
RBTL3预测结果随机性

### ISSUE THREAD

**Issue by aiaiyueq11** [ymcui/Chinese-BERT-wwm#101]
请问下我用RBTL3接CRF做NER任务，训练完成后，对于同一条数据多次预测结果都不一样。但是我换成其他预训练模型结果就一致了，RBTL3模型内部有这方面的限制吗。

**Comment by ymcui** [comment]
没有的，RBTL3只是把RoBERTa-large模型砍成三层之后进行进一步预训练的。
你接CRF之后BERT部分参与训练了吗？

**Comment by ymcui** [comment]
没有收到新的回复。如果有其他问题请随时reopen。
