### ISSUE TITLE
下载

### ISSUE THREAD

**Issue by jianwei-song** [ymcui/Chinese-BERT-wwm#102]
你好，请问一下中文预训练模型的下载链接失效了，谷歌和讯飞云的都下载不了，可以麻烦分享一下百度云的么

**Comment by ymcui** [comment]
具体是哪个模型？谷歌云的不存在分享时间，应该不会失效。

**Comment by ymcui** [comment]
经测试讯飞盘相关链接也是正常的，建议排查一下自己的网络是否有问题。

**Comment by jianwei-song** [comment]
你好！
我想下载这个模型BERT-wwm-ext，早上我又尝试下载，谷歌的下载显示网络有问题，应该是被墙了，或者别的原因，然后讯飞的下载链接没问题，但是点击下载后跳转到迅雷下载后一直显示任务链接超时，我尝试了其他模型也是下载不了，我在迅雷查看任务来源时显示要登录讯飞云统一认证平台，这个云我注册不了。所以可以的话麻烦您分享一下这个模型的百度云链接。谢谢！


| |
宋建炜
|
|
sjwmmt@163.com
|
签名由网易邮箱大师定制
在2020年4月10日 08:21，Yiming Cui<notifications@github.com> 写道：

具体是哪个模型？谷歌云的不存在分享时间，应该不会失效。

**Comment by ymcui** [comment]
麻烦直接用浏览器下载，速度还是可以的，迅雷的话可能会被限制。

**Comment by jianwei-song** [comment]
好的，我换了浏览器可以下载了，谢谢您耐心解答！
祝好！


| |
宋建炜
|
|
sjwmmt@163.com
|
签名由网易邮箱大师定制
在2020年4月10日 11:27，Yiming Cui<notifications@github.com> 写道：

麻烦直接用浏览器下载，速度还是可以的，迅雷的话可能会被限制。

**Comment by sshimii** [comment]
> 好的，我换了浏览器可以下载了，谢谢您耐心解答！ 祝好！ | | 宋建炜 | | sjwmmt@163.com | 签名由网易邮箱大师定制 在2020年4月10日 11:27，Yiming Cui<notifications@github.com> 写道： 麻烦直接用浏览器下载，速度还是可以的，迅雷的话可能会被限制。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

大佬，可以提供一下百度网盘的分享嘛？讯飞一直登录不上去，没外网登不上谷歌云。
