### ISSUE TITLE
使用Transformers加载模型

### ISSUE THREAD

**Issue by MaxMaxinne** [ymcui/Chinese-BERT-wwm#103]
请问我使用如下方法加载模型时，Transformers是会重新下载模型还是可以使用我已经下载好的模型呢？
tokenizer = BertTokenizer.from_pretrained("MODEL_NAME")
model = BertModel.from_pretrained("MODEL_NAME")

**Comment by ymcui** [comment]
是从s3上下载下来的，具体参考hugggingface transformers相关接口定义。

**Comment by MaxMaxinne** [comment]
> 是从s3上下载下来的，具体参考hugggingface transformers相关接口定义。

好的谢谢您！
