### ISSUE TITLE
关于Squad方案bert+AoA+DAE

### ISSUE THREAD

**Issue by dkicenan** [ymcui/Chinese-BERT-wwm#109]
您好：
    我在做机器阅读理解任务时，采用您那边夺冠方案（bert+AoA+DAE），想请教bert和AoA是如何结合的？我是在bert之后加了AoA，但是效果不理想。

祝好！谢谢！

**Comment by ymcui** [comment]
由于本问题与仓库内容无关，我先关闭issue了。

P.S. 上面提到的阅读理解方案并非公开工作，所以非常抱歉的是暂时无法提供相关信息。
