### ISSUE TITLE
Pytorch版能直接在transformers里面用吗？

### ISSUE THREAD

**Issue by sqlkrad** [ymcui/Chinese-BERT-wwm#110]
在transformers的[模型库](https://huggingface.co/hfl/chinese-bert-wwm-ext#)里看到文件包括下面6个：

File name | Last modified | File size
-- | -- | --
added_tokens.json | Thu, 19 Dec 2019 09:48:22 GMT | 2.0B
config.json | Fri, 31 Jan 2020 23:00:25 GMT | 805.0B
pytorch_model.bin | Thu, 19 Dec 2019 09:48:16 GMT | 392.5MB
special_tokens_map.json | Thu, 19 Dec 2019 09:48:22 GMT | 112.0B
tokenizer_config.json | Thu, 19 Dec 2019 09:48:21 GMT | 19.0B
vocab.txt | Thu, 19 Dec 2019 09:48:21 GMT | 107.0KB

但是google drive[下载](https://drive.google.com/file/d/1iNeYFhCBJWeUsIlnW_2K6SMwXkM4gLb_/view)里面只有三个文件。

**Comment by ymcui** [comment]
旧版transformers只需要3个文件：model，vocab，config。
新版transformers里把tf模型转成pt就是6个文件了，多出来的都是一些config，没多大用处。

added_tokens.json
```json
{}(base)
```

special_tokens_map.json
```json
{"unk_token": "[UNK]", "sep_token": "[SEP]", "pad_token": "[PAD]", "cls_token": "[CLS]", "mask_token": "[MASK]"}
```

tokenizer_config.json
```json
{"init_inputs": []}
```

**Comment by sqlkrad** [comment]
好的，谢谢！
