### ISSUE TITLE
MaskedLM的head能开源吗？

### ISSUE THREAD

**Issue by snakeztc** [ymcui/Chinese-BERT-wwm#111]
现在提供的模型只包含WWM fine tune 完成的BERT模型。能同时提供论文中用来fine tune 的MLM的linear head 吗？

**Comment by ymcui** [comment]
你好，这部分的确没有包含，暂时无法提供。
你可以用自己的数据继续学习MLM，不会有太大的偏差，因为hidden->vocab这个weight实际上调用的是embedding matrix，除此之外的可训练的参数量已经很少了。

**Comment by snakeztc** [comment]
谢谢回复。所以你们在学习MLM的时候，hidden -> vocab是用word embedding初始化的吗？在MLM训练的时候 hidden -> vocab还继续和word embedding绑定吗？还是是独立的两个module？

**Comment by ymcui** [comment]
可以看一下BERT原版的实现，具体看这里：https://github.com/google-research/bert/blob/master/run_pretraining.py#L257
