### ISSUE TITLE
中文文本里面混有韩文的时候tokenize会出错

### ISSUE THREAD

**Issue by sqlkrad** [ymcui/Chinese-BERT-wwm#113]
一个韩文的字符会被拆成两个，很奇怪

环境：pytorch, transformers

虽然一些分类问题没什么影响，但是像token tagging之类的问题就会有些麻烦

**Comment by ymcui** [comment]
你可以考虑在tokenizer中加入韩文unicode的特殊处理来避免这个问题。

**Comment by sqlkrad** [comment]
但是这个应该是属于tokenizer的bug？因为我觉得把一个字符拆成两个字符怎么说都不是一个合理的操作……而且不保证除了韩文以外其他的字符不会出现这个问题。

**Comment by ymcui** [comment]
抱歉，暂时没有时间细致排查解决这个问题。
tokenizer也并不是我们原创的代码。如有必要的话还请自行修改调试，感谢理解。

**Comment by sqlkrad** [comment]
其他版本的BERT，比如百度的ERNIE就没有这个问题，所以才在这里提issue的，应该是您的模型的问题。

**Comment by ymcui** [comment]
谷歌官方的中文BERT是否出现这个问题？ 我们的词表和谷歌原版的词表是一致的，前处理和模型本身并没有什么直接联系。
