### ISSUE TITLE
请问同一个模型（如RoBERTa-wwm-ext, Chinese），tensorflow版和pytorch版，模型输出是一样的吗

### ISSUE THREAD

**Issue by LowinLi** [ymcui/Chinese-BERT-wwm#114]
请问同一个模型（如RoBERTa-wwm-ext, Chinese），tensorflow版和pytorch版，模型输出是一样的吗？

**Comment by ymcui** [comment]
权重是一样的，但因为框架不同以及随机性等原因，没法保证输出一定是一模一样的，但应该在合理的误差范围内。

**Comment by LowinLi** [comment]
> 权重是一样的，但因为框架不同以及随机性等原因，没法保证输出一定是一模一样的，但应该在合理的误差范围内。

谢谢，我两个版本的向量不一样，但是下游任务表现差不多，和您说的一样

**Comment by ymcui** [comment]
好的，那我就先关闭issue了。🤝
