### ISSUE TITLE
请问一下roberta-wwm的输入的ids最大size是不是512 ?

### ISSUE THREAD

**Issue by Hanshawn11** [ymcui/Chinese-BERT-wwm#115]

**Comment by ymcui** [comment]
是指input length吗？如果不进行额外处理的话最大长度是512。

**Comment by Hanshawn11** [comment]
> 是指input length吗？如果不进行额外处理的话最大长度是512。
感谢！
对，是input length，就是说encode text的时候， 指定max length不可以大过512.

**Comment by ymcui** [comment]
可以大于512，但是效果会有下降，因为预训练时的最大长度是512。
或者你可以自己写切片逻辑，将输入文本切成若干块，每块不大于512，最后再用一定的逻辑将输出结果进行融合。

**Comment by Hanshawn11** [comment]
encode超过512会有一个CUDA ERROR.

**Comment by ymcui** [comment]
如果自己不想写切片逻辑的话，在前处理代码里加上>512的情况下直接截断到512。

**Comment by Hanshawn11** [comment]
好的， 感谢回复！
