### ISSUE TITLE
请问预训练过程中的标点符号是用的中文还是英文？

### ISSUE THREAD

**Issue by renli1024** [ymcui/Chinese-BERT-wwm#116]
您好，非常感谢您开源了这么好的工作。

目前我在使用您预训练好的模型进行微调，因为我这边的数据很脏，标点符号存在中英夹杂的情况，在数据预处理过程我计划统一转为中文或英文的符号，所以想问下您预训练时是如何进行数据预处理的呢（尤其在标点符号这方面），我希望和您的处理策略保持一致。

感谢！

**Comment by ymcui** [comment]
你好，
1）我们在前处理的时候并没有对标点符号进行特殊处理（数据来源主要是新闻等比较规整的数据）。
2）如果你的数据中存在大量中英文符号混杂的情况，我建议统一处理为中文标点。但对于一些数字的小数点、英文缩写等必须使用英文标点的情况需要进行特殊保护处理。
3）如果占比并不大的话，也可以不进行特殊处理，模型通过统计规律会学习到正确的匹配模式。

**Comment by renli1024** [comment]
了解，感谢您的解答 :)
