### ISSUE TITLE
看表格感觉是 中文是字级别的mask，英文是全词mask？

### ISSUE THREAD

**Issue by guotong1988** [ymcui/Chinese-BERT-wwm#117]
![image](https://user-images.githubusercontent.com/4702353/81800005-bda14900-9544-11ea-9159-436140d3c3f3.png)
@ymcui 
谢谢！！

**Comment by ymcui** [comment]
中文也是词级别。
图中`模型`和`预测`两个词中的每个字都是被同时mask的

**Comment by guotong1988** [comment]
知道了，`同时`这两个字用的好：）
