### ISSUE TITLE
can not use model by transformers

### ISSUE THREAD

**Issue by guoxiaojun1999** [ymcui/Chinese-BERT-wwm#118]
I tried to use chinese roberta model according to this url https://huggingface.co/hfl/chinese-roberta-wwm-ext
<img width="425" alt="nlp error 2" src="https://user-images.githubusercontent.com/34236162/82270565-cb712700-99a7-11ea-914f-85cf0fb9a7a7.png">

But it does not work and raises error like this
<img width="543" alt="nlp error1" src="https://user-images.githubusercontent.com/34236162/82270526-b0061c00-99a7-11ea-9a98-a73bb4a82cf9.png">

**Comment by ymcui** [comment]
Hi,
Please use `BertTokenizer` and `BertModel`, as indicated in https://github.com/ymcui/Chinese-BERT-wwm/blob/master/README_EN.md#huggingface-transformers
I have just tested under `transformers==2.9.1`, and everything goes well.

**Comment by ymcui** [comment]
Close this issue since no further discussions on this topic.
Feel free to reopen if necessary.
