### ISSUE TITLE
ner预测问题

### ISSUE THREAD

**Issue by ak47-1234** [ymcui/Chinese-BERT-wwm#12]
您上面发的ner代码（https://github.com/ProHiryu/bert-chinese-ner/blob/master/BERT_NER.py），对于token切词后后面的sub_token对应的标签设置为了X，哪这样跑出的结果这个X是怎么处理的？

**Comment by ymcui** [comment]
实测基本不影响结果。
你可以做一些解码的规则，比如：
1. 前面一个是`B-`，则X替换为`I-`
2. 前面一个是`I-`，则X替换为`I-`
3. 前面一个是`O`，则X替换为`O`
然后把转换后的序列标签送入seqeval计算P/R/F。
