### ISSUE TITLE
关于mlm训练方式数据输入形式的问题

### ISSUE THREAD

**Issue by cobraheleah** [ymcui/Chinese-BERT-wwm#124]
你好，我想问一下，基于wwm的预训练方式只用到了mlm，并没有用到nsp，是不是输入的训练数据预处理后开头和结尾都没有[cls]和[sep]了，就只是每个字符在词表中的对应id

**Comment by ymcui** [comment]
本目录中的所有模型的输入方式和原版BERT一致，[CLS]和[SEP]都需要加。
