### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by Thornhill-GYL** [ymcui/Chinese-BERT-wwm#126]
请问如何获取下载模型文件的链接？想通过服务器直接下载，麻烦了！

**Comment by stvhuang** [comment]
Take `hfl/chinese-roberta-wwm-ext-large` for example, open this [https://huggingface.co/hfl/chinese-roberta-wwm-ext-large](https://huggingface.co/hfl/chinese-roberta-wwm-ext-large#), then click __List all files in model__ near the bottom of that page, and you can see the link

**Comment by Thornhill-GYL** [comment]
thanks!
