### ISSUE TITLE
how to convert chinese bert to tensorflow 2.0 

### ISSUE THREAD

**Issue by lai-agent-t** [ymcui/Chinese-BERT-wwm#128]
HI, How to convert chinese bert to tensorflow 2.0? 
the official github shows below: 
https://github.com/tensorflow/models

**Comment by ymcui** [comment]
Hi,
I'm sorry that I don't have an experience on tf2, and can not provide support for your question.
Probably you can convert PyTorch models into tf2 via a script under transformers library (https://github.com/huggingface/transformers/blob/master/src/transformers/convert_pytorch_checkpoint_to_tf2.py), but there is no guarantee that this will work (untested).

**Comment by lai-agent-t** [comment]
Thanks for you reply, huggingface one seems doesn't work right now and I use this one 
https://github.com/tensorflow/models/blob/master/official/nlp/bert/tf2_encoder_checkpoint_converter.py
and it works. Thanks!
