### ISSUE TITLE
Release of MacBERT pretrained model

### ISSUE THREAD

**Issue by stvhuang** [ymcui/Chinese-BERT-wwm#129]
As title. Is there any plan to release the [MacBERT](https://arxiv.org/abs/2004.13922) pretrained model?

**Comment by ymcui** [comment]
Thank you for contacting. 
As our paper is under review, we're unable to provide these resources at the moment. 
Once there is an update, we'll update our paper on arXiv.

**Comment by stvhuang** [comment]
I see. Wait for your good news.
