### ISSUE TITLE
tf模型权重文件

### ISSUE THREAD

**Issue by Yb-Z** [ymcui/Chinese-BERT-wwm#134]
你好，请问一下： 
为什么下载下来的tf版model，权重文件的命名是bert_model.ckpt.data-00000-of-00001？而不是bert_model.ckpt
这个在pretrain load时候会报错
![image](https://user-images.githubusercontent.com/57145931/89294532-38848680-d692-11ea-90b2-12c1eaf7b563.png)

**Comment by ymcui** [comment]
你好，谷歌原版英文权重的命名也是如此的。加载的时候传入`bert_model.ckpt`。
