### ISSUE TITLE
求Longformer的预训练语言模型

### ISSUE THREAD

**Issue by Maybewuss** [ymcui/Chinese-BERT-wwm#135]

**Comment by jeffery0628** [comment]
+1

**Comment by ymcui** [comment]
你好，感谢给出建议，我们会认真考虑一下，谢谢。

**Comment by renxingkai** [comment]
+10086，等不及了，哈哈

**Comment by jeffery0628** [comment]
参考longformer的脚本写了用中文预训练bert生成longformer模型的blog，在ner任务上做了一些实验，效果没有下降，证明方法可行，同学可以参考这篇博客http://www.jeffery.ink/2020/07/29/transformers/longformer/
