### ISSUE TITLE
请问模型训练细节中Training Tokens 如何计算的？

### ISSUE THREAD

**Issue by LeoWood** [ymcui/Chinese-BERT-wwm#136]
您好，在模型细节中提到bert原始的training tokens是0.4B，而加入extend数据之后的traning tokens是5.4B。因为这边也有准备一些额外的预训练数据，想进行一个量级上的对比。想问下这个training tokens数量具体是如何计算的？
例如：[CLS][SEP]这些特殊标记有没有算进去，如果是512长度的数据，padding部分的tokens也算进去了么？一般预训练数据还会做Duplicate，这里是否重复计算了呢？

**Comment by ymcui** [comment]
你好，训练token数量是以原始训练语料（即生成tf_records之前）进行统计的。中文以“字”进行切分，英文则以“词”进行切分。因此不存在将`[CLS]`或者`padding`位纳入考虑的情况。

**Comment by LeoWood** [comment]
> 你好，训练token数量是以原始训练语料（即生成tf_records之前）进行统计的。中文以“字”进行切分，英文则以“词”进行切分。因此不存在将`[CLS]`或者`padding`位纳入考虑的情况。

那是不是可以这么理解，这个tokens数量就是将原始语料用BERT-tokenizer跑一遍，统计出来的结果？

**Comment by ymcui** [comment]
并不是，tokenizer会把英文切成子词。不过考虑到语料主要是中文，这个差别可以忽略。
