### ISSUE TITLE
您好 请问您的团队是否有在包含2020年新冠肺炎的相关语料上做过fine tune?

### ISSUE THREAD

**Issue by mzh1996** [ymcui/Chinese-BERT-wwm#137]
您好 请问您的团队是否有在包含2020年新冠肺炎的相关语料上做过fine tune?
最近在做一个相关的情感分析  可能需要用得到这些
谢谢

**Comment by ymcui** [comment]
你好，暂时没有这方面的领域预训练模型。

**Comment by mzh1996** [comment]
> 你好，暂时没有这方面的领域预训练模型。

好的 收到 我自己搞一个试试看
