### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by lzl19971215** [ymcui/Chinese-BERT-wwm#140]
您好，请问加载TFBertModel时出现  NotImplementedError: Weights may only be loaded based on topology into Models when loading TensorFlow-formatted weights (got by_name=True to load_weights)报错是什么原因导致的呢？

**Comment by ymcui** [comment]
你用的是TF2吗？目录中的权重是TF1.X的。

**Comment by lzl19971215** [comment]
> 你用的是TF2吗？目录中的权重是TF1.X的。

哦哦，我用的是TF2。那如果我用1.60版本pytorch的话，可以直接加载pytorch版的模型吗？

**Comment by ymcui** [comment]
PyTorch 1.5试过是可以的，1.6应该问题不大，你可以试一下。

**Comment by lzl19971215** [comment]
> PyTorch 1.5试过是可以的，1.6应该问题不大，你可以试一下。

好的，如果用huggingface transformers的版本必须是2.2.2吧？我最开始用3.0.2报错了

**Comment by ymcui** [comment]
2.x应该都可以的，最新测试过2.10可以加载。
3.x最近才出还没进行尝试。

**Comment by lzl19971215** [comment]
> 2.x应该都可以的，最新测试过2.10可以加载。
> 3.x最近才出还没进行尝试。

好的，非常感谢！
