### ISSUE TITLE
权重版本问题

### ISSUE THREAD

**Issue by HUSTHY** [ymcui/Chinese-BERT-wwm#142]
请问怎么把你们预训练好的TensorFlow版本的权重转化为transformers 3.0+ 中tf2.0可以使用的tf_model.h5模型

**Comment by ymcui** [comment]
抱歉，本目录中的模型均只在transformers 2.X + TensorFlow 1.12 ~ 1.15测试通过。其余版本还请你去transformers目录中查找相关解决方案。

P.S. 中文和英文BERT仅权重不同，适配方法应该是一致的。

**Comment by otto248** [comment]
作者你好，尝试用tensorflow 1.15 + transformer 2.10加载，但是一直有如下的报错

Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index'] found in directory /home/...

**Comment by HUSTHY** [comment]
谢谢作者的回复，上面那个怎么将预训练好的TensorFlow版本的权重转化为transformers 3.0+ 中tf2.0可以使用的tf_model.h5模型的问题，我用其他的方案解决了。

**Comment by HUSTHY** [comment]
> 作者你好，尝试用tensorflow 1.15 + transformer 2.10加载，但是一直有如下的报错
> 
> Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index'] found in directory /home/...

你这个明显是权重路径不对，或者没有'tf_model.h5', 'model.ckpt.index'这两种格式的权重文件

**Comment by HUSTHY** [comment]
> 抱歉，本目录中的模型均只在transformers 2.X + TensorFlow 1.12 ~ 1.15测试通过。其余版本还请你去transformers目录中查找相关解决方案。
> 
> P.S. 中文和英文BERT仅权重不同，适配方法应该是一致的。

谢谢作者的回复，上面那个怎么将预训练好的TensorFlow版本的权重转化为transformers 3.0+ 中tf2.0可以使用的tf_model.h5模型的问题，我用其他的方案解决了。

**Comment by otto248** [comment]
> > 作者你好，尝试用tensorflow 1.15 + transformer 2.10加载，但是一直有如下的报错
> > Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index'] found in directory /home/...
> 
> 你这个明显是权重路径不对，或者没有'tf_model.h5', 'model.ckpt.index'这两种格式的权重文件

路径核实过了 没有问题；加载torch版本就没问题；加载tf的就报错

**Comment by jk123vip** [comment]
> > 抱歉，本目录中的模型均只在transformers 2.X + TensorFlow 1.12 ~ 1.15测试通过。其余版本还请你去transformers目录中查找相关解决方案。
> > P.S. 中文和英文BERT仅权重不同，适配方法应该是一致的。
> 
> 谢谢作者的回复，上面那个怎么将预训练好的TensorFlow版本的权重转化为transformers 3.0+ 中tf2.0可以使用的tf_model.h5模型的问题，我用其他的方案解决了。

请问下你是怎样解决的？
