### ISSUE TITLE
transformer2.2.2 加载参数失败

### ISSUE THREAD

**Issue by RoacherM** [ymcui/Chinese-BERT-wwm#144]
直接加载会报错
OSError: Model name '/Users/wonbyron/bert/chinese_roberta_wwm_large_ext_pytorch/' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased). We assumed '/Users/wonbyron/bert/chinese_roberta_wwm_large_ext_pytorch/config.json' was a path or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.
经检查,应该将config文件改成bert.config才行

**Comment by ymcui** [comment]
没太明白你的意思，是指config文件内容有问题还是加载的时候config文件名有问题？

**Comment by RoacherM** [comment]
transformer2.2.2 默认加载的是config.json而不是bert_config.json,提供的原始参数文件应该采用前者命名而不是后者,否则回报错

**Comment by ymcui** [comment]
了解。本目录并不会一直适配新的transformer库，所以请按需修改文件名以适配新版本。
