### ISSUE TITLE
请问什么时候可以提供GPT2之类的CLM的预训练语言模型

### ISSUE THREAD

**Issue by piekey1994** [ymcui/Chinese-BERT-wwm#148]
目前中文环境好像一直没有找到一个特别好用的CLM语言模型

**Comment by ymcui** [comment]
感谢建议，目前暂时没有这方面的计划。
看到GitHub上已经有一些中文GPT2的资源了，不妨去尝试一下。

**Comment by JiaqiYao** [comment]
你把152关掉了，我就这里回复你吧。如果你试试transformers库的分类模型，就会发现它调用pooler_fc_size设置分类最后一层参数的输入的size。而且只要原版如此，就不管对错，也不分析，有点不大好吧
