### ISSUE TITLE
pytorch模型是用pytorch代码预训练的还是tf预训练后转成pytorch的？

### ISSUE THREAD

**Issue by daniellibin** [ymcui/Chinese-BERT-wwm#154]
作者你好，我这有几个疑问，还请帮忙解答，谢谢。
1.pytorch模型是用pytorch代码预训练的还是tf预训练后转成pytorch的？
2.如果是tf预训练后转成pytorch的，那用tf和pytorch加载模型进行训练两者的差别大不大？
3.roberta是否采用了动态掩码方式进行预训练的？
谢谢

**Comment by ymcui** [comment]
1. TF转PT，用huggingface的脚本。
2. 原则上不应该有很大的区别，但存在一定的随机性，你可以在你的任务上多次运行后对比看看。
3. 否，还是静态masking。
