### ISSUE TITLE
wwm是否可以提取固定向量？

### ISSUE THREAD

**Issue by 1535966643** [ymcui/Chinese-BERT-wwm#155]
您好，请问是否wwm是否也是可以像谷歌bert一样，Using BERT to extract fixed feature vectors呢

**Comment by ymcui** [comment]
可以的，wwm只影响pre-train，不影响应用。

**Comment by 1535966643** [comment]
谢谢，RoBERTa和bert这两种预训练模型在使用时候有什么区别吗？中文的

**Comment by ymcui** [comment]
并没有，两者是可以无缝替换的，直接修改对应的模型路径即可。

**Comment by 1535966643** [comment]
谢谢您，非常感谢
