### ISSUE TITLE
计算序列长度大于512的向量

### ISSUE THREAD

**Issue by EnvoyX** [ymcui/Chinese-BERT-wwm#158]
当前模型中`max_seq_len`可以设定的最大值为512；而在[https://github.com/hanxiao/bert-as-service](url)中介绍参数`max_seq_len`时说“longer sequence will be trimmed on the right side”。请问有什么方法可以得到序列长度大于512的向量吗？

**Comment by ymcui** [comment]
最简单的方法是将输入切片&分别输到BERT，然后把输出向量拼起来。
要麻烦一点的话就是改造成Longformer。这里有一篇相关介绍：https://jeffery0628.github.io/2020/07/29/longformer/

**Comment by EnvoyX** [comment]
感谢回复，想问一下第一种方法里把两个向量拼起来是指直接做平均或者加权平均吗？

**Comment by EnvoyX** [comment]
找到了以前提问的相关问题，谢谢您耐心回复
