### ISSUE TITLE
模型都接入到transformers，tensorflow也支持吗

### ISSUE THREAD

**Issue by shulongdeng22** [ymcui/Chinese-BERT-wwm#159]
本目录发布的模型已接入Huggingface-Transformers。在transformers中使用这些模型的话，只支持pytorch吗？是不是不支持tensorflow ，按照官方的例子使用pythorch是可以调用的，但是使用tensorflow就会报错

**Comment by ymcui** [comment]
是的，只支持PyTorch，早期没有放TF2的文件。
你可以把TF1.X的模型转换成TF2.X的格式。https://github.com/ymcui/Chinese-BERT-wwm/issues/156
