### ISSUE TITLE
tensorflow版本和hugging face torch版本的weights是否一致？

### ISSUE THREAD

**Issue by iamlxb3** [ymcui/Chinese-BERT-wwm#16]
我目前测下来tf和torch在同一文本的embedding好像不一样

**Comment by ymcui** [comment]
是同一个tensorflow权重转换的，你可以用tensorflow权重自行转换为pytorch。
pytorch版本的权重仅作为参考，如果我们发现pytorch结果异常会更新相关内容。

**Comment by ymcui** [comment]
你好，经过我们检查，并没有发现异常。方便提供一下具体的测试样例吗？我们使用的是pytorch-bert官方提供的notebook进行对比检查的。
