### ISSUE TITLE
有没有可以区分英文的大小写的chinese-bert-wwm模型

### ISSUE THREAD

**Issue by sunxiaojie99** [ymcui/Chinese-BERT-wwm#163]
好像现在的模型通过huggingface加载后，处理中英混杂的句子分词时，会把英文转成小写，有没有可以保持原大小写的版本呀

**Comment by ymcui** [comment]
并没有，这需要重新训练。如果需要将文本还原为true case，可以参照阅读理解的做法，建立一个分词前后的映射表然后进行还原。

**Comment by sunxiaojie99** [comment]
怎么建立分词前后的映射表呢 可以给个例子吗 是需要自己拼凑吗

**Comment by ymcui** [comment]
https://github.com/google-research/bert/blob/master/run_squad.py#L309
看看这里吧
