### ISSUE TITLE
大佬，讯飞云下载下面的rbt4可以开放一下吗？

### ISSUE THREAD

**Issue by zhusleep** [ymcui/Chinese-BERT-wwm#169]
能不能给个下载链接？谢谢了。

**Comment by ymcui** [comment]
我看了一下，下载链接是正常的。
http://pan.iflytek.com/link/7B04C5BF09812DB241BBA973D649824C
密码e8dN

**Comment by zhusleep** [comment]
多谢，我之前尝试下载，一直提示我要登陆科大内部页面。另外我在移动端也正常下载了。
