### ISSUE TITLE
wwm训练的模型，如何使用bert的tokenize？

### ISSUE THREAD

**Issue by nathinal** [ymcui/Chinese-BERT-wwm#170]
您好，我有几个问题，想咨询一下：
1、中文使用WWM预训练时，会将"公司" tokenize 为 [“公”,"##司"]，mask时，会将"公司"mask为“[[MASK],[MASK]]”，请问此时label是["公","司"]还是["公","##司"]？
2、如果label使用的是["公","##司"]来训练的话，那么训练的就是“##司”，而不是“司”；那么在后续模型的使用时，使用bert的BertTokenizer，只会将"公司"tokenize为[“公”,"司"]，但是按照WWM的思想，应该要tokenize 为 [“公”,"##司"]。“##司”和“司”二者的embeddings是不一样的。后续模型的使用，是不是也需要分词？
麻烦帮忙解答一下！！！谢谢

**Comment by ymcui** [comment]
1. 你理解错了。“公司”用wordpiece并不会分成”公，##司“。加##只是wwm算法为了方便识别词边界加入的，实际的输入还是”公，司“，对应label也是一样的。 总结：”公，##司“只是一个中间状态，既不会用在输入也不会用在输出。
2. 不存在2的问题。

**Comment by nathinal** [comment]
masked_lm_labels其实是“公”“司”是吧

 

发件人: Yiming Cui <notifications@github.com>
答复: ymcui/Chinese-BERT-wwm <reply@reply.github.com>
日期: 2021年1月28日 星期四 18:06
收件人: ymcui/Chinese-BERT-wwm <Chinese-BERT-wwm@noreply.github.com>
抄送: nathinal <1094401269@qq.com>, Author <author@noreply.github.com>
主题: Re: [ymcui/Chinese-BERT-wwm] wwm训练的模型，如何使用bert的tokenize？ (#170)

 
你理解错了。“公司”用wordpiece并不会分成”公，##司“。加##只是wwm算法为了方便识别词边界加入的，实际的输入还是”公，司“，对应label也是一样的。 总结：”公，##司“只是一个中间状态，既不会用在输入也不会用在输出。
不存在2的问题。

**Comment by nathinal** [comment]
我还有一个问题：

那如果输入到模型的tokens和labels中中文都去掉了##，那bert提供的vocab.txt中的##司这些，有什么作用了。

 

发件人: Yiming Cui <notifications@github.com>
答复: ymcui/Chinese-BERT-wwm <reply@reply.github.com>
日期: 2021年1月28日 星期四 18:06
收件人: ymcui/Chinese-BERT-wwm <Chinese-BERT-wwm@noreply.github.com>
抄送: nathinal <1094401269@qq.com>, Author <author@noreply.github.com>
主题: Re: [ymcui/Chinese-BERT-wwm] wwm训练的模型，如何使用bert的tokenize？ (#170)

 
你理解错了。“公司”用wordpiece并不会分成”公，##司“。加##只是wwm算法为了方便识别词边界加入的，实际的输入还是”公，司“，对应label也是一样的。 总结：”公，##司“只是一个中间状态，既不会用在输入也不会用在输出。
不存在2的问题。

**Comment by ymcui** [comment]
不是去掉，是原来wordpiece分出来是什么样就用什么样的输入输出。词表里的’##‘前导的单词是原来词表里就有的，至于为什么会有，我也不清楚。

**Comment by nathinal** [comment]
请问训练使用的分词工具和结巴差距大吗？

发件人: Yiming Cui <notifications@github.com>
答复: ymcui/Chinese-BERT-wwm <reply@reply.github.com>
日期: 2021年1月28日 星期四 20:40
收件人: ymcui/Chinese-BERT-wwm <Chinese-BERT-wwm@noreply.github.com>
抄送: nathinal <1094401269@qq.com>, Author <author@noreply.github.com>
主题: Re: [ymcui/Chinese-BERT-wwm] wwm训练的模型，如何使用bert的tokenize？ (#170)

 

不是去掉，是原来wordpiece分出来是什么样就用什么样的输入输出。词表里的’##‘前导的单词是原来词表里就有的，至于为什么会有，我也不清楚。

**Comment by ymcui** [comment]
不清楚，原则上不会有太大差别。

**Comment by nathinal** [comment]
好的，非常感谢！！！

 

发件人: Yiming Cui <notifications@github.com>
答复: ymcui/Chinese-BERT-wwm <reply@reply.github.com>
日期: 2021年1月29日 星期五 07:50
收件人: ymcui/Chinese-BERT-wwm <Chinese-BERT-wwm@noreply.github.com>
抄送: nathinal <1094401269@qq.com>, Author <author@noreply.github.com>
主题: Re: [ymcui/Chinese-BERT-wwm] wwm训练的模型，如何使用bert的tokenize？ (#170)

 

不清楚，原则上不会有太大差别。

**Comment by ymcui** [comment]
不客气，那我就先关闭了。

**Comment by nathinal** [comment]
好的

 

发件人: Yiming Cui <notifications@github.com>
答复: ymcui/Chinese-BERT-wwm <reply@reply.github.com>
日期: 2021年1月29日 星期五 14:47
收件人: ymcui/Chinese-BERT-wwm <Chinese-BERT-wwm@noreply.github.com>
抄送: nathinal <1094401269@qq.com>, Author <author@noreply.github.com>
主题: Re: [ymcui/Chinese-BERT-wwm] wwm训练的模型，如何使用bert的tokenize？ (#170)

 

不客气，那我就先关闭了。
