### ISSUE TITLE
论文中说create_pretraining_data.py放在了git rep中，我看这个目录下没有数据处理的这个脚本，请问在哪个rep中呢？

### ISSUE THREAD

**Issue by PearlW1** [ymcui/Chinese-BERT-wwm#171]
“We use official create pretraining data.py to convert raw input text to the pre-training examples, which was provided in BERT GitHub repository”，请问这里的github repository是哪个呢？求链接~

**Comment by ymcui** [comment]
https://github.com/google-research/bert/blob/master/create_pretraining_data.py

**Comment by PearlW1** [comment]
感恩告知~
