### ISSUE TITLE
相同配置代码，重复运行结果不同？

### ISSUE THREAD

**Issue by sirlb** [ymcui/Chinese-BERT-wwm#172]
你好，我们的BERT-wwm-ext（tf）模型做ner和情感分类任务，在相同的配置也指定了随机种子的情况下，两次运行结果不同，换了google的BERT或roBERTa都不会出现这个问题。用部分样本训练发现，样本不多（20条）时结果是一样的，但训练样本大以后，结果就不同了。不知道什么原因，谢谢你的解答。

**Comment by sirlb** [comment]
补充：直接冻结bert参数，只训练其他层，两次结果一样。

**Comment by ymcui** [comment]
TensorFlow下并不能保证指定random_seed的情况下结果相同，尤其在GPU/TPU这种计算设备下。
PyTorch下基本不会出现这个问题。

**Comment by sirlb** [comment]
谢谢回复，我们是用gpu，您的意思是TensorFlow不能保证所有BERT模型在指定random_seed下有相同结果吗？
但是我设置了TensorFlow后，其他几个BERT模型和RoBERTa是有相同的结果。谢谢。

**Comment by sirlb** [comment]
感谢回复，我们使用了本目录中的四个模型
1.RoBERTa-wwm-ext, Chinese  TensorFlow
2.BERT-wwm, Chinese  TensorFlow
3.BERT-base, Chinese  Google TensorFlow
4.BERT-wwm-ext, Chinese   TensorFlow
其中只有BERT-wwm-ext这个模型不能得到相同结果，其他三个可以。

**Comment by sirlb** [comment]
感谢回复，我们使用了本目录中的四个模型
1.RoBERTa-wwm-ext, Chinese  TensorFlow
2.BERT-wwm, Chinese  TensorFlow
3.BERT-base, Chinese  Google TensorFlow
4.BERT-wwm-ext, Chinese   TensorFlow
其中只有BERT-wwm-ext这个模型不能得到相同结果，其他三个可以。

**Comment by ymcui** [comment]
看起来是比较奇怪的。BERT-wwm和BERT-wwm-ext只是在训练数据上有所区别。
用BERT-wwm-ext进行训练的话，不同run之间的差异有多大呢？如果很大的话，建议先用其他模型。

**Comment by sirlb** [comment]
你好，以下是我们运算10次的结果，其中测试集的差异较大。
val [0.726592, 0.735065, 0.731458, 0.728426, 0.731893, 0.7375, 0.724269, 0.728426, 0.736709, 0.732997]

test [0.630435, 0.706468, 0.692683, 0.679058, 0.670702, 0.692033, 0.679803, 0.706876, 0.694611, 0.706601]
