### ISSUE TITLE
Chinese-BERT-wwm fine-tuning

### ISSUE THREAD

**Issue by nietao2** [ymcui/Chinese-BERT-wwm#18]
请问使用Chinese-BERT-wwm做fine-tuning的时候需要用LTP做分词吗？

**Comment by ymcui** [comment]
不需要的，和普通的BERT一样，使用的是Char级别的Tokenizer。
Whole Word Masking只影响预训练阶段的Mask方式，并不改变下游任务的输入方式。

**Comment by nietao2** [comment]
谢谢！

**Comment by guotong1988** [comment]
为什么fine-tune的时候不需要分词？
