### ISSUE TITLE
RBTL3和RBT3的三层是怎么选取的？

### ISSUE THREAD

**Issue by MingFL** [ymcui/Chinese-BERT-wwm#182]
RBTL3和RBT3的三层是怎么选取的？

**Comment by MingFL** [comment]
不是结构，想问的是初始化的三层参数

**Comment by syzong** [comment]
modeling.py 文件的 get_assignment_map_from_checkpoint（）
这个函数里面改代码，用 var.name 判断，然后只加载你要的参数

**Comment by MingFL** [comment]
> modeling.py 文件的 get_assignment_map_from_checkpoint（）
> 这个函数里面改代码，用 var.name 判断，然后只加载你要的参数

想了解的问题和参数加载无关，README.md中写道：
一、RBT3：由RoBERTa-wwm-ext 3层进行初始化，继续训练了1M步
       RBTL3：由RoBERTa-wwm-ext-large 3层进行初始化，继续训练了1M步
二、直接使用RoBERTa-wwm-ext-large前三层进行初始化并进行下游任务的训练将显著降低效果，例如在CMRC 2018上测试集仅能达到42.9/65.3，而RBTL3能达到63.3/83.4

从上述描述可以理解，RBT和RBTL都是从wwm-ext(-large)中选择了三层进行了初始化，再进行1M步的训练。并且直接使用前三层不额外训练的情况下效果不佳，所以想请问 RBT3和RBTL3选择的三层是不是wwm-ext(-large)最初的三层？
