### ISSUE TITLE
关于用bert_base训练THUCNNews的结果

### ISSUE THREAD

**Issue by vencent-debug** [ymcui/Chinese-BERT-wwm#186]
您好，在用bert复现结果时，在学习率设置为5e-5时，在整体一个14类14万新闻上跑出来的效果是91%～93%，请问一下您，在训练时，是否需要注意一些具体问题。如果有的话，希望您能指导一下。

**Comment by vencent-debug** [comment]
数据为每类随机抽取，在训练时已打乱

**Comment by ymcui** [comment]
你好，我们使用的是10分类的新闻数据。
数据地址在这里：https://github.com/gaussic/text-classification-cnn-rnn
数据不同的话，结果不太具有可比性，所以你可以先在这个10分类的集合上跑一下看看有没有问题。
