### ISSUE TITLE
我猜 Whole Word Masking (wwm) 实际是一种更高效的方式，字级别增加预训练时间和随机性 也能达到同样最终效果吧？

### ISSUE THREAD

**Issue by guotong1988** [ymcui/Chinese-BERT-wwm#187]
@ymcui 多谢！

**Comment by guotong1988** [comment]
@ymcui THX！

**Comment by ymcui** [comment]
你指的`字级别增加预训练时间和随机性`很难达到，况且本身算力就是很大的瓶颈，不宜用完全随机性换取有效性。WWM每次都是选取整词进行处理，如果完全依靠随机性，一个句子中恰好所有被mask的位置都是整词的概率会很低。
