### ISSUE TITLE
为什么RoBERTa版本训练速度更慢？

### ISSUE THREAD

**Issue by sunyilgdx** [ymcui/Chinese-BERT-wwm#189]
老师您好，有一个不太成熟的问题，通过一段时间的简单使用，发现在相同的参数设置下（TensorFlow）RoBERTa版本的训练和推理速度明显慢于普通的BERT版本，不知道这是不是我使用时的问题，还是确实存在这方面的现象？

**Comment by ymcui** [comment]
你好，你是应用在什么任务呢？具体使用的是哪个模型？大概慢多少？
