### ISSUE TITLE
实验结果复现问题

### ISSUE THREAD

**Issue by houjin0803** [ymcui/Chinese-BERT-wwm#196]
老师，您好，我使用的是您仓库中的CMRC2018代码来进行做抽取式阅读理解任务的。有个问题想请教老师，就是运行代码中有个参数是--do_train，这个参数设置为True是不是就是代表需要进行预训练呢？我把这个参数设置为false，然后将vocab_file，bert_config_file，init_checkpoint都更改为wwm模型的，但结果和您论文中结果相差很大。如果将do_train设置为true，它不就要进行预训练了，但是这个CMRC2018源码是参考BERT的，所以MASK方式并不是遮盖全词。希望老师能解答一下，谢谢老师！以下是我的启动命令。
python run_cmrc2018_drcd_baseline.py 
--vocab_file=/etc/houjin/MyDrive/cmrc2018/bert_wwm/vocab.txt 
--bert_config_file=/etc/houjin/MyDrive/cmrc2018/bert_wwm/bert_config.json 
--init_checkpoint=/etc/houjin/MyDrive/cmrc2018/bert_wwm/bert_model.ckpt 
--do_train=True 
--do_predict=True
 --train_file=/etc/houjin/MyDrive/cmrc2018/data/cmrc2018_train.json 
--predict_file=/etc/houjin/MyDrive/cmrc2018/data/cmrc2018_dev.json 
--train_batch_size=32 
--num_train_epochs=2 
--max_seq_length=128 
--doc_stride=128 
--learning_rate=3e-5 
--save_checkpoints_steps=1000 
--output_dir=/etc/houjin/MyDrive/cmrc2018/output 
--do_lower_case=False
 --use_tpu=False

**Comment by ymcui** [comment]
1）do_train是表示要finetune
2）mask的方式不会影响下游finetune

**Comment by houjin0803** [comment]
好的，谢谢老师！
