### ISSUE TITLE
求教：为什么词语要对应多个mask？

### ISSUE THREAD

**Issue by fangwc** [ymcui/Chinese-BERT-wwm#197]
mask 过程中， 现在虽然是词语会被同时mask掉， 但是比如一个词语2个字符现在对应2个mask， 为什么不是词语就是对应一个mask  即使有多个字符？   求教

**Comment by ymcui** [comment]
如果两个字符对应一个mask，那预测的时候预测什么呢？预测空间，即词表是以字符（WordPiece级别）构成的。
