### ISSUE TITLE
基于分词预训练中文Bert

### ISSUE THREAD

**Issue by AliceBruce** [ymcui/Chinese-BERT-wwm#20]
模型训练也是基于和Bert相同的vocab.txt是吧？
是每次mask的时候，会先判断前后是否能组成一个词，将能组成词的字全都mask是吧？
我对nlp不太了解哈，我想问下如果是基于词来训练一个模型的话，是不是词典也应该是由词组成的呀？我理解目前mask的方法是不是只是多了mask的数量，可能相关的字会有影响，但是最后如果想要输出词向量的话，是不是还是基于字的呀？

**Comment by ymcui** [comment]
1. 模型训练也是基于和Bert相同的vocab.txt是吧？
`是`
2. 是每次mask的时候，会先判断前后是否能组成一个词，将能组成词的字全都mask是吧？
`是先分词，然后对一个词内的所有元素进行mask（广义）`
3. 如果是基于词来训练一个模型的话，是不是词典也应该是由词组成的呀？
`是的，理论上是可以训练一个以”词“为单位的BERT`
4. 最后如果想要输出词向量的话，是不是还是基于字的呀？
`是`
