### ISSUE TITLE
model sizing of ”BERT-wwm-ext, Chinese” and ”BERT-wwm, Chinese” 

### ISSUE THREAD

**Issue by elulue** [ymcui/Chinese-BERT-wwm#203]
Hi, I found the size of model ”BERT-wwm-ext, Chinese” and ”BERT-wwm, Chinese” are similar, all around 365MB, I thought the sizing of extended model should be larger, could you please help to confirm it?
Thanks a lot.

**Comment by ymcui** [comment]
They are all base-level PLMs. `ext` means the PLM is trained with extended data. Nothing related to the model size.

**Comment by elulue** [comment]
Thanks a lot.
