### ISSUE TITLE
The way to get Chinese Word Embedding.

### ISSUE THREAD

**Issue by qhd1996** [ymcui/Chinese-BERT-wwm#208]
For some reason I need to get the Chinese word embedding based on PLM, would you offor some ways to get them based on the existing trained models? Thanks :)

**Comment by ymcui** [comment]
Please see https://github.com/google-research/bert#using-bert-to-extract-fixed-feature-vectors-like-elmo
With this script, you can extract word representation of any layers in BERT.

**Comment by qhd1996** [comment]
> Please see https://github.com/google-research/bert#using-bert-to-extract-fixed-feature-vectors-like-elmo With this script, you can extract word representation of any layers in BERT.

Thank you very much!
