### ISSUE TITLE
讯飞的下载链接提示外链已经过期了

### ISSUE THREAD

**Issue by natureLanguageQing** [ymcui/Chinese-BERT-wwm#211]
讯飞的下载链接提示外链已经过期了

**Comment by ymcui** [comment]
感谢告知，近期会上传到百度云和阿里云做分流。
如果着急的话可以告诉我你需要哪个模型，我开一个临时的链接。

**Comment by ymcui** [comment]
百度网盘链接已更新。

**Comment by natureLanguageQing** [comment]
太谢谢你啦，你可真好。

**Comment by natureLanguageQing** [comment]
我在做一个实验，尝试统计自然语言处理的分词 基于 textrank和tfidf构建有限特征的idea是否可以进一步提高模型准确率。降低模型参数量。
