### ISSUE TITLE
请问RoBERTa-wwm-ext有没有随机初始化MLM部分的权重

### ISSUE THREAD

**Issue by dolphin-Jia** [ymcui/Chinese-BERT-wwm#212]
我看到苏剑林的博客中有提到“哈工大开源的RoBERTa-wwm-ext-large则不知道出于什么原因随机初始化了MLM部分的权重”，所以也想请问一下RoBERTa-wwm-ext有没有这么做？

**Comment by ymcui** [comment]
公开的版本只包含transformer部分的权重，如需做MLM任务请自行二次预训练task head。
至于说MLM部分被随机初始化，是因为二次保存的时候（为了删掉adam相关参数以减小体积）预训练脚本导致。
