### ISSUE TITLE
pad_token_id错误

### ISSUE THREAD

**Issue by CaoYiwei** [ymcui/Chinese-BERT-wwm#214]
您好，huggingface上chiniese-roberta-wwm-ext模型的config.json的pad_token_id是1，应该是0

**Comment by CaoYiwei** [comment]
额，不止这一个模型的pad_token_id有问题，麻烦您改一下

**Comment by ymcui** [comment]
你好，感谢告知。
已修改`chinese-roberta-wwm-ext`和`chinese-roberta-wwm-ext-large`。

**Comment by CaoYiwei** [comment]
> 

thx~

**Comment by ustcdane** [comment]
hi, @ymcui   "今天[MASK]情很好"
发现huggingfacechinese-roberta-wwm-ext-large  还有 github chinese_roberta_wwm_large_ext_pytorch.zip   
给出的结果比较奇怪：篝、颼

**Comment by ustcdane** [comment]
好像是 这个原因: https://github.com/ymcui/Chinese-BERT-wwm/issues/76
