### ISSUE TITLE
有点晕：『开源版本不包含MLM任务的权重』,这句话是什么意思？

### ISSUE THREAD

**Issue by caihua-liang** [ymcui/Chinese-BERT-wwm#226]
文中提到了一句：

注意：开源版本不包含MLM任务的权重；如需做MLM任务，请使用额外数据进行二次预训练（和其他下游任务一样）

我理解BERT的预训练模型会使用MLM和NSP两种训练模式，并且主要使用了MLM训练，那么不包含MLM任务的权重是啥意思？

**Comment by chansonZ** [comment]
同问
