### ISSUE TITLE
 CJRC有预训练的模型么？

### ISSUE THREAD

**Issue by ucas010** [ymcui/Chinese-BERT-wwm#229]
hi，dear大佬
关于CJRC的预训练模型，下面都是么？是通用的？
<img width="867" alt="image" src="https://user-images.githubusercontent.com/50656998/224007664-84a6f9b9-1283-41eb-a7e1-ac6fdcf1afb7.png">
这些在huggingface可以直接用？

**Comment by ymcui** [comment]
并没有现成的CJRC上精调过的模型。这里的结果需要自己在相应的模型上用CJRC数据精调。
