### ISSUE TITLE
链接失效求助

### ISSUE THREAD

**Issue by Alternate-D** [ymcui/Chinese-BERT-wwm#231]
崔先生您好！之前您为某位网友解答问题时提供了如下链接：
https://github.com/ymcui/CMRC2018-DRCD-BERT
但是现在这个链接失效了，请问现在对应的链接是哪个呢？

**Comment by ymcui** [comment]
因为已经archive处理了，你可以参考以下备份内容。
[CMRC2018-DRCD-BERT-master.zip](https://github.com/ymcui/Chinese-BERT-wwm/files/11128641/CMRC2018-DRCD-BERT-master.zip)
