### ISSUE TITLE
Is there any sharing about phoneme-BERT pretrained?

### ISSUE THREAD

**Issue by JohnHerry** [ymcui/Chinese-BERT-wwm#238]
Thanks for sharing.  As to the speech domain, we need some LM trained with phonemes, eg. PinYin or IPA,  Is there any such results for sharing?

**Comment by ymcui** [comment]
Sorry, I'm not aware of these models, as our models are not related to speech processing.

**Comment by JohnHerry** [comment]
Thanks.
