### ISSUE TITLE
Is onnx  model available

### ISSUE THREAD

**Issue by panxin801** [ymcui/Chinese-BERT-wwm#239]
Hello sir, thank you for your sharing. I'd like to ask if there's onnx model of RoBERTa-wwm-ext-large is available now, thank you for your reply

**Comment by ymcui** [comment]
I'm sorry that we don't have ONNX version at hand. 
You might have to convert our TensorFlow/PyTorch model by yourself.

**Comment by panxin801** [comment]
I get it thank you sir

**Comment by Liucy122** [comment]
Have you successfully converted the ONNX model file? I am using torch 2.4.0 and converting ONNX with 🤗 Optimum on a GPU 3090 , but the inference speed is slower than that of PyTorch. Have you encountered this situation?
