### ISSUE TITLE
关于阅读理解的问题

### ISSUE THREAD

**Issue by zhezhaoa** [ymcui/Chinese-BERT-wwm#24]
您好打扰您了。我看您的论文里面，对阅读理解数据集使用的长度是512。但是阅读理解任务很多答案的位置（answer_start）超过512，对于这些答案您是怎么处理的呢？

**Comment by ymcui** [comment]
请参考谷歌官方run_squad.py脚本的做法，是对篇章做了切片处理。
https://github.com/google-research/bert/blob/master/run_squad.py#L350
