### ISSUE TITLE
模型转换失效，请求提供pytorch版本

### ISSUE THREAD

**Issue by braveryCHR** [ymcui/Chinese-BERT-wwm#25]
可能由于操作原因，我使用pytorch-transformers进行模型转化，然而tf checkpoints转为pytorch模型后，发生模型无效果，基本等同于随机的现象，希望能够提供转换好的版本，麻烦您啦
转换命令为：
` sudo python3 convert.py --tf_checkpoint_path ./bert_model.ckpt.index   --bert_config_file bert_config.json  --pytorch_dump_path ./pytorch_bert.bin
`
其中convert.py的代码为：
[https://github.com/huggingface/pytorch-transformers/blob/master/pytorch_transformers/convert_tf_checkpoint_to_pytorch.py](链接)

**Comment by ymcui** [comment]
sure，会用最新版的[PyTorch-Transformers](https://github.com/huggingface/pytorch-transformers)转换一版，你今天晚些时候再来看看。

**Comment by ymcui** [comment]
Google Drive的链接已添加，讯飞云今晚会传。

**Comment by ymcui** [comment]
讯飞云链接已补齐，关闭issue
