### ISSUE TITLE
「THUCNews：篇章级文本分类」任务的评测结果

### ISSUE THREAD

**Issue by bigrat911** [ymcui/Chinese-BERT-wwm#26]
「THUCNews：篇章级文本分类」任务的训练和测试集是如何选取的？
因为Readme里只说了，“采用的是其中一个子集，需要将新闻分成10个类别中的一个。 ”
但是是哪个子集？
另外性能指标是F值吗？是宏平均还是微平均

**Comment by ymcui** [comment]
请查看对应目录：https://github.com/ymcui/Chinese-BERT-wwm/tree/master/data/thucnews
分类任务评测指标的都是accuracy，参考BERT的run_classifier.py
