### ISSUE TITLE
文本分类问题

### ISSUE THREAD

**Issue by xudekuan** [ymcui/Chinese-BERT-wwm#27]
请问在进行文本分类时，各文本的句子数目是不一样的，是如何提取的文本特征的呢？

**Comment by ymcui** [comment]
句子数目不一样不影响，粘在一起当作一个长的序列输到BERT里就可以了。

**Comment by xudekuan** [comment]
模型是否有长度的限制？如果有限制，规定长度后的都截断了，是不是会影响效果？

**Comment by ymcui** [comment]
训练时候的最大长度是512，和原版BERT一直。
至于截断问题你可以参考run_squad.py的做法，将长文本进行切片处理。
https://github.com/google-research/bert/blob/master/run_squad.py

**Comment by xudekuan** [comment]
非常感谢您的回复。

**Comment by ymcui** [comment]
不客气，本issue关闭。
