### ISSUE TITLE
如何移除训练用的变量

### ISSUE THREAD

**Issue by stevewyl** [ymcui/Chinese-BERT-wwm#30]
当继续进行预训练后，模型保存的checkpoint有1.2G左右，其中包含大量反向传播用的node，而在微调的时候是用不到这些变量的，如何去除这些node，让模型大小保持在400M左右。我只搜到了freeze_graph工具，但这样模型就不能继续训练了。想问下你们是怎么做的？谢谢！🙏

**Comment by ymcui** [comment]
here it is: https://github.com/ymcui/Chinese-BERT-wwm/issues/22
