### ISSUE TITLE
关于模型选择的疑问

### ISSUE THREAD

**Issue by buptzcW** [ymcui/Chinese-BERT-wwm#31]
您好，想问一下，如果我使用的中文数据已经脱敏映射为数字，并且是按照单个字进行了切分，例如：我爱共产党 ---->我/爱/共/产/党---->232 323 45 990 43。在这样的场景下，我应该用基于英文的bert模型还是用基于中文的bert模型呢

**Comment by ymcui** [comment]
这个已经超出本仓库的讨论范畴了。建议你两者都尝试一下。
