### ISSUE TITLE
DRCD數據集，在前處理時卡住

### ISSUE THREAD

**Issue by chiangyulun0914** [ymcui/Chinese-BERT-wwm#32]
使用Bert-Chinese實現在DRCD數據集時，在前處理的部分卡住，如下圖
![image](https://user-images.githubusercontent.com/36063123/63396407-8ceb1380-c3f9-11e9-96d0-96cd23ee406b.png)

卡在40年這裡，就一動也不動了，不確定是甚麼問題造成..

------------------------------------------------------------------
附上我的scripts:

```
#### local path
DRCD_DIR=raw_data/
INIT_CKPT_DIR=BERT/bert_pretrain_model/chinese_L-12_H-768_A-12
MODEL_DIR=BERT/experiment/chinese_L-12_H-768_A-12

CUDA_VISIBLE_DEVICES=0,1 python BERT/bert/run_squad.py \
  --vocab_file=$INIT_CKPT_DIR/vocab.txt \
  --bert_config_file=$INIT_CKPT_DIR/bert_config.json \
  --init_checkpoint=$INIT_CKPT_DIR/bert_model.ckpt \
  --do_train=True \
  --train_file=$DRCD_DIR/DRCD_training.json \
  --do_predict=True \
  --predict_file=$DRCD_DIR/DRCD_dev.json \
  --train_batch_size=64 \
  --learning_rate=3e-5 \
  --num_train_epochs=2.0 \
  --max_seq_length=512 \
  --doc_stride=128 \
  --output_dir=$MODEL_DIR/model_ckpt \
  --use_tpu=False \
  --tpu_name=$TPU_NAME \
  --version_2_with_negative=False \
  --do_lower_case=True
```

**Comment by ymcui** [comment]
你可以打印一下具体是处理到哪个sample出了问题。前处理过程还没进入到model里，所以和model没什么关系。
比如在`convert_examples_to_features`最外层的for循环添加一个计数器：
```
def convert_examples_to_features(examples, tokenizer, max_seq_length,
                                 doc_stride, max_query_length, is_training,
                                 output_fn):
  """Loads a data file into a list of `InputBatch`s."""

  unique_id = 1000000000

  for (example_index, example) in enumerate(examples):
    if example_index % 100 == 0:
      tf.logging.info("%d example processed" % (example_index))
    ...
```

**Comment by chiangyulun0914** [comment]
感謝您的回覆，我在這裡加了一行，print 目前處理的example_index
![image](https://user-images.githubusercontent.com/36063123/63400955-3cc77d80-c408-11e9-91c3-7f4bf35cf50c.png)

發現在第19個example之後的部分，如圖
![image](https://user-images.githubusercontent.com/36063123/63401008-6aacc200-c408-11e9-85f1-b5d5acb40975.png)

看起來是因為反白的部分所致，只在前19個example才print東西出來，實際上第20個example以後，程式仍有在進行。
![image](https://user-images.githubusercontent.com/36063123/63401311-6f25aa80-c409-11e9-8131-fda95da08c45.png)

非常感謝您提供的建議!!
