### ISSUE TITLE
请问mask策略

### ISSUE THREAD

**Issue by hzrpku** [ymcui/Chinese-BERT-wwm#33]
请问你们的策略是只对词进行mask并预测，还是说是随机的（既有词也有单字）。

**Comment by ymcui** [comment]
分词之后的整个词，不会出现只mask一个词中的部分字。要注意的是一个词中的所有字的mask方式（[mask]，随即替换，保留原字）是随机的。

**Comment by hzrpku** [comment]
我明白，我的意思是 如果分词后：【我 爱 自然 语言 处理】 你们是只会对多字组成的词（【自然】、【语言】、【处理】）mask，还是说 【我】、【爱】都有可能会被mask。

**Comment by ymcui** [comment]
`我` `爱` 这也是词啊，单个字的词。

**Comment by hzrpku** [comment]
get!  多谢
