### ISSUE TITLE
关于词典的问题

### ISSUE THREAD

**Issue by anuoeattoomuch** [ymcui/Chinese-BERT-wwm#35]
这个模型真是太棒了！请问一个小小的问题，
按照示例：
[Original Sentence]
使用语言模型来预测下一个词的probability。
[Original Sentence with CWS]
使用 语言 模型 来 预测 下 一个 词 的 probability 。
[Original BERT Input]
使 用 语 言 [MASK] 型 来 [MASK] 测 下 一 个 词 的 pro [MASK] ##lity 。
[Whold Word Masking Input]
使 用 语 言 [MASK] [MASK] 来 [MASK] [MASK] 下 一 个 词 的 [MASK] [MASK] [MASK] 。

应该是按照分词的结果，组成词的前后字都会被mask，那就不应该存在 “##一” 这类中文词的替换问题，为啥词典里还有很多中文“##一 ”这类词呢？这些词存在的意义是什么呢？另外我也看了  #13 的回答，希望能得到回答，谢谢！

**Comment by ymcui** [comment]
我们使用的是谷歌官方Chinese BERT中的`vocab.txt`，并未重新生成新词表。
这些带`##`token应该是WordPiece生成出来的，具体我没有去细看。
