### ISSUE TITLE
Some question about training with LCQMC dataset

### ISSUE THREAD

**Issue by EdwardMao** [ymcui/Chinese-BERT-wwm#36]
Hi,
Thank you for this wonderful work.
But when I use this pre-trained model to fine-tune on LCQMC dataset, the result is not satisfying, which is 83.5%, about 4% lower than average. Could you please provide more detailed  training setting?
Now I set nums_epoch to 3, learning_rate to 2e-5, maxlen to 128, batch to 64, warm_up_steps to 10%, everything else is default. I have tried to increase batch_size and nums_epoch but it did not help.
I would appreciate if you give some suggestion.
Thanks!
Best,

**Comment by ymcui** [comment]
Could you reproduce the result using Google's Chinese BERT?

**Comment by EdwardMao** [comment]
Unfortunately, no.

**Comment by ymcui** [comment]
In this case, I think you should reproduce the results on Google's Chinese BERT first. 
Similar results were also reported by [ERNIE](https://github.com/PaddlePaddle/ERNIE#results-on-semantic-similarity).
