### ISSUE TITLE
same corpus

### ISSUE THREAD

**Issue by Icyzrw** [ymcui/Chinese-BERT-wwm#37]
MSRA 和 人民日报的数据 好像是一样的？

**Comment by ymcui** [comment]
MSRA: https://github.com/OYE93/Chinese-NLP-Corpus
PD: https://github.com/ProHiryu/bert-chinese-ner/tree/master/data

**Comment by Icyzrw** [comment]
Sorry to bother again ><
但是我check了这两份数据里面的内容，训练数据里的句子真的非常相似，MSRA里的msra_test_bio.txt 文件和PD的dev.txt也基本相同。

**Comment by ymcui** [comment]
MSRA应该是对的，人民日报的数据建议你也用这个目录下的：https://github.com/OYE93/Chinese-NLP-Corpus/tree/master/NER/People's%20Daily
PD相关结果就暂时不要参考了，会重新跑一下更新。

**Comment by ymcui** [comment]
目前看到人民日报数据网上也是参差不齐，没有一个”官方“下载渠道。
论文上的结果是用https://github.com/ProHiryu/bert-chinese-ner/tree/master/data 数据做的，结果上没有问题。但是不是”原版PD“就不得而知了。如果你要写在paper里，建议多渠道了解一下这个数据是否有”官方版本“。

**Comment by Icyzrw** [comment]
这个是ERNIE提供的MSRA数据集https://bj.bcebos.com/paddlehub-dataset/msra_ner.tar.gz。
内容与https://github.com/OYE93/Chinese-NLP-Corpus的MSRA数据集仿佛大不相同。反而与其中人民日报的数据相似（dev）。
感觉现在很难找到到底哪家提供的数据是权威的，如果数据不同，模型之间的比较就只能靠自己的复现来做了。
感谢您耐心的回答~
