### ISSUE TITLE
请问有fine tune代码提供吗

### ISSUE THREAD

**Issue by shizhediao** [ymcui/Chinese-BERT-wwm#44]
请问可以提供fine tune的代码吗？
我目前借鉴谷歌的代码但是NER task无法复现结果，想看看ft代码是否一致
谢谢

**Comment by ymcui** [comment]
NER数据集可能存在一定问题 相关结果请勿参考

**Comment by shizhediao** [comment]
什么问题呢？你们的bert-wwm论文中的NER结果是不能参考了是吗？
你说的NER数据集存在的问题是什么？

**Comment by ymcui** [comment]
是的 目前网上流传的数据划分都不太一样 请在自己的数据上比对 不要参考文中数字

**Comment by shizhediao** [comment]
我也发现数据划分存在很多不同的版本。不过我看你们论文中写的很清楚

> Note that, ERNIE used a different division that has 21k/2.3k/4.6k in train/dev/test (did not use full original train/test). We use the official MSRA- NER train and test set in the following experiments. 
我这边要在MSRA-NER上做对比试验，你们论文汇报的结果就是在你们采用的MSRA数据集上的结果是把？
我和你用的一样的数据集，所以说对比起来还是有意义的？

**Comment by ymcui** [comment]
参考 #7

**Comment by shizhediao** [comment]
thanks
