### ISSUE TITLE
RoBERTa这个模型，取消了NSP loss以后，[CLS] 或者说 <S> 这个初始token是如何得到的呢？

### ISSUE THREAD

**Issue by wangruichens** [ymcui/Chinese-BERT-wwm#47]
在原BERT模型里，[CLS]主要是通过NSP任务来训练embedding的。 那在RoBERTa里面没了NSP loss了，为什么取头部token做分类也能得到很好的效果呢？

**Comment by ymcui** [comment]
这个目录里面的并不是严格意义上的RoBERTa，因为模型是从BERT做初始化，会保留CLS那部分的权重。

**Comment by wangruichens** [comment]
谢谢解释。那顺便再请教一下，单纯讲RoBERTa， 为什么它也能在分类任务上跑出高分呢？ 我看原paper里没有提到关于<S> or [CLS] 的训练方法，如何得到它们的embedding呢？

**Comment by wangruichens** [comment]
想通了，因为attention机制的存在,CLS本身并不需要训练。
