### ISSUE TITLE
关于BPE tokenizer没有在项目里提及

### ISSUE THREAD

**Issue by A-Rain** [ymcui/Chinese-BERT-wwm#49]
您好，我有个疑问，就是roberta原文中采用的是BPE Tokenizer，然而好像SCIR中的roberta-wwm好像仍然采用的是bert的一系列（Bertconfig, BertTokenizer，就是hugginface pytorch_tranformer里面的类）,所以模型的整体依旧是bert-wwm，只是训练的方式仿照roberta中训练的吗

**Comment by ymcui** [comment]
RoBERTa-style BERT
