### ISSUE TITLE
roberta模型加载错误

### ISSUE THREAD

**Issue by BinNong** [ymcui/Chinese-BERT-wwm#52]
在使用pytorch_transfomers加载chinese_roberta_wwm_ext_pytorch报错。（ 使用【RobertaConfig, RobertaForSequenceClassification, RobertaTokenizer】加载）

**Comment by ymcui** [comment]
https://github.com/ymcui/Chinese-BERT-wwm#faq 看最后一条

**Comment by BinNong** [comment]
> https://github.com/ymcui/Chinese-BERT-wwm#faq 看最后一条

get it
