### ISSUE TITLE
预训练数据清洗问题

### ISSUE THREAD

**Issue by sunyilgdx** [ymcui/Chinese-BERT-wwm#53]
您好，请问一下，在使用预训练语料时有没有对语料进行一定的清洗，比如说统一全角与半角，或者删除不必要的特殊符号，在下游任务中是否需要进行同样的处理，如果不处理会不会导致模型的finetune效果变差？谢谢！

**Comment by ymcui** [comment]
你所提到的清洗是没有的。最大限度的保留原始文本的特性，避免给下游任务数据处理带来太多限制。
