### ISSUE TITLE
请问有遇到过这个错的吗

### ISSUE THREAD

**Issue by George191** [ymcui/Chinese-BERT-wwm#60]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-52-d4eebbc9a335> in <module>()
----> 1 train_model_pred, test_model_pred = run_cv(10, DATA_LIST, None, DATA_LIST_TEST)
      2 test_pred = [np.argmax(x) for x in test_model_pred]
      3 test_df['label'] = test_pred
      4 test_df[['id', 'label']].to_csv('baseline3.csv', index=None)

4 frames
/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py in input_shape(self)
    887             return unpack_singleton(input_shapes)
    888         else:
--> 889             raise AttributeError('The layer "' + str(self.name) +
    890                                  ' has multiple inbound nodes, '
    891                                  'with different input shapes. Hence '

AttributeError: The layer "model_14 has multiple inbound nodes, with different input shapes. Hence the notion of "input shape" is ill-defined for the layer. Use `get_input_shape_at(node_index)` instead

**Comment by ymcui** [comment]
麻烦先用谷歌原版BERT测试，如果也报同样的错误，那就不是本目录下的预训练模型的问题。
