### ISSUE TITLE
请教一下输入token如果是词内部的字，使用的token是'字'还是'##字'?

### ISSUE THREAD

**Issue by yangxudong** [ymcui/Chinese-BERT-wwm#62]
我注意到bert官方提供的中文vocab.txt里，每个汉字都有两个token，一个带有'##'前缀，一个不带前缀，我的理解是不带前缀的表示词的首字，带前缀的是非首字。由于两者转换为id后并不相同，我想请教一下对应词内非首字，训练数据的输入是否使用带前缀的token？另外，MLM的label是否使用带前缀的版本？不胜感激！

**Comment by ymcui** [comment]
两个问题的答案是一样的：原版BERT你是怎么用的，这个就怎么用。
WordPiece tokenizer会把英文切成带'##'的token，而中文会按字进行切分。
wwm只改变masking，不改变输入输出的原始格式。

**Comment by ShenYounger** [comment]
> 两个问题的答案是一样的：原版BERT你是怎么用的，这个就怎么用。
> WordPiece tokenizer会把英文切成带'##'的token，而中文会按字进行切分。
> wwm只改变masking，不改变输入输出的原始格式。

有一点没有想明白。为什么原始bert中文模型里面的词典，里面有'##'鹏这样的东西存在呢？按理来说，有'鹏'不是已经足够了么？

**Comment by ReactiveCJ** [comment]
> 只改变masking，不改变输入输出的原始格式。

作者没有修改过原版的词表，所以这是google训练的基座tokenizer自带的 ##字 这样的， google为啥出来这个，感觉很奇怪
