### ISSUE TITLE
如何使用google bert 训练好的checkpoint在自己的语料上继续训练

### ISSUE THREAD

**Issue by RyanHuangNLP** [ymcui/Chinese-BERT-wwm#65]
您好，我看到BERT-wwm模型细节的init_checkpoint是使用google bert，我自己尝试发现如果直接加载原始的checkpoint文件，会报错：
```
ERROR:tensorflow:Error recorded from training_loop: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

From /job:worker/replica:0/task:0:
Key bert/embeddings/LayerNorm/beta/adam_m not found in checkpoint
	 [[node save/RestoreV2 (defined at /usr/local/lib/python3.6/di
```

我觉得这是因为在模型训练结束后，为了减少模型的size，将adam相关的变量去除了，现在需要重新加载继续预训练，是需要在checkpoint文件加入adam的变量才能实现在google原始bert上再继续训练吗？

**Comment by ymcui** [comment]
init_checkpoint指定初始化模型（比如google bert）之后只会读取和你代码里匹配的权重，不匹配的不会读进去。请检查是否是output_dir里有其他model。

**Comment by RyanHuangNLP** [comment]
@ymcui 谢谢回复，我再检查一下自己的代码

**Comment by MingFL** [comment]
这个问题有解决吗，遇到了相同的问题。 embeddings/LayerNorm/beta/Adam not found in checkpoint
