### ISSUE TITLE
关于在您发布的预训练模型之上进一步预训练

### ISSUE THREAD

**Issue by zhezhaoa** [ymcui/Chinese-BERT-wwm#66]
您好打扰您了
我用您的roberta模型进行微调效果很好
但是我加载您的roberta-large模型，在我的语料上进一步预训练，一上来的mlm准确率是0。我也用完形填空试了一下，确实模型不能进行准确的预测。所以我猜测您的预训练roberta-large模型的最上层（单词预测）是不是有一些问题?
我试过了google发布的模型，包括中文的和英文的base、large模型，不存在这样的问题
期待您的回复～

**Comment by ymcui** [comment]
因为这部分权重没有保留，直接测效果肯定不会好。建议用你自己的数据迭代一段时间之后再进行测试。顶层的权重与任务密切相关，相对来说比较容易学习。

**Comment by zhezhaoa** [comment]
多谢您的回答
所以下面这些项的参数是怎么得到的呢？
![image](https://user-images.githubusercontent.com/10495098/67677112-2583ae00-f9be-11e9-80eb-6d8a808f0ade.png)

**Comment by ymcui** [comment]
BERT官方的run_pretraining.py的get_masked_lm_output函数里有对应的层。
如果你继续pre-train的话从random开始训练就可以了。

**Comment by zhezhaoa** [comment]
嗯嗯多谢
所以您的roberta-large的一些参数，比如softmax层参数（cls.predictions.decoder.weight [21128*1024]) 是随机初始化的哈？

**Comment by ymcui** [comment]
是的

**Comment by ewrfcas** [comment]
崔老师，近期有一些有意思的自监督BERT任务，需要有MLM这层的权重来做一些预测，可惜这部分权重在large模型失效了(base正常）。不知道后期能否补充？
