### ISSUE TITLE
Roberta预训练时，学习率是多少

### ISSUE THREAD

**Issue by policeme** [ymcui/Chinese-BERT-wwm#72]
@ymcui 
你好
1. 你们预训练Roberta base的时候学习率初始化是多少，warmup rate是多少诶
2. 如果我要在你们预训练模型的基础上再继续训练我的学习率跟 warmup rate应该设置为多少诶

**Comment by ymcui** [comment]
1) lr=1e-4, warm up=10k steps
2) 继续训练学习率需要减少很多，比如1e-5，具体跟你自己的数据量有关系，请自行调参。

**Comment by ymcui** [comment]
可以参考https://openreview.net/pdf?id=Syx4wnEtvH 的Table 4。

**Comment by policeme** [comment]
好的，多谢

**Comment by policeme** [comment]
如果把你的训练步数换算成epoch的话，总共有多少个epoch诶
