### ISSUE TITLE
关于训练语料生成时候的分句

### ISSUE THREAD

**Issue by ShenYounger** [ymcui/Chinese-BERT-wwm#73]
你好。作者。我现在的情况是这样，我拿了一批中文文本，希望在你们开源的模型上接着重新训练模型。整个流程，我是这么想的：

a.对中文文本进行分句。产生训练数据的input。(格式是一行一句话，但是两个文档之间用空行分割)
b.对create_pretraining_data.py和tokenization.py进行修改，把我使用的分词算法嵌套进去(因为我使用的是公司内部的分词模型)，修改原来的mask，产生全词mask。
c.产生训练数据以后就好办了，后面用原始的bert python脚本run_pretraining.py进行再训练就好了。

是这么流程么？另外，在对中文文本进行分句的时候，你们是用什么技术进行的分句？谢谢！

**Comment by ymcui** [comment]
是的，基本流程就是这样。
分句我们采用的就是简单的规则切分（句号，问号，感叹号），这样效率高一些。
当然你也可以采用LTP等工具进行切分。

**Comment by ShenYounger** [comment]
> 是的，基本流程就是这样。
> 分句我们采用的就是简单的规则切分（句号，问号，感叹号），这样效率高一些。
> 当然你也可以采用LTP等工具进行切分。

谢谢作者您的及时回复，感谢！

**Comment by bbinwang** [comment]
mark

**Comment by YinlongLiu-source** [comment]
mark
