### ISSUE TITLE
Do you have plans to release Chinese ALBERT model?

### ISSUE THREAD

**Issue by cmxcn** [ymcui/Chinese-BERT-wwm#77]
Thanks for the great work of Chinese roberta-large, do you have plans to release ALBERT models? Looking forward to it!

**Comment by cmxcn** [comment]
many thanks, I've tried that one, but it doens't work well on my classification task. Just found you also released a XLNet model, will git it a try :)

**Comment by ymcui** [comment]
Feel free to re-open if necessary.
