### ISSUE TITLE
Some questions about the RoBERTa-wwm-ext-large

### ISSUE THREAD

**Issue by h12345jack** [ymcui/Chinese-BERT-wwm#79]
Hello, It's a nice work for developers.

I am using these pre-train-models to some tasks. 
It works in the BERT-wwm-ext with  Huggingface's pytorch-bert.

As you said, 
```
文本不需要经过分词，wwm只影响预训练过程，不影响下游任务的输入
```
However, when I use the RoBERTa-wwm-ext-large. I have a question.

In [Huggingfac's documents](https://huggingface.co/transformers/model_doc/roberta.html#transformers.RobertaTokenizer),it looks like we need two files: **vocab_file**, **merges_file**

How to deal with it? Just use the Bert's tokenizer?
Thank you

**Comment by ymcui** [comment]
Load our RoBERTa(-like BERT) using BERT's interface.
