### ISSUE TITLE
请问一下，我用bert-as-service去启动整个模型有一些问题

### ISSUE THREAD

**Issue by EmptyChan** [ymcui/Chinese-BERT-wwm#8]
用[bert-as-service](https://github.com/hanxiao/bert-as-service)启动整个模型做词嵌入，原来的bert模型是直接输入一句话，然后产生一串词向量。但是没有经过分词，就直接输入的一句话。现在用这个wwm模型，我是否需要进行改变一下？改用分词后的结果（list或者空格连接的str）输入模型，获得词向量？
主要原因是采用原来的bert预训练模型，在加上决策树等分类方法，发现文本分类的精度有0.8以上。用了wwm只有0.2了。。。不知道哪里有问题。

**Comment by ymcui** [comment]
和原始的BERT是一样的。
Whole word masking**只改变预训练阶段的训练样本生成方式**。
在下游任务做微调时，仍然采用WordPiece tokenizer进行分词，中文会被切成字，英文会被切成WordPiece tokens。

TL;DR: 对于BERT-wwm来说，原来BERT输入什么，你就用什么。

**Comment by EmptyChan** [comment]
好的~~谢谢了，我再看看哪一个地方错误了。3q
