### ISSUE TITLE
外链失效

### ISSUE THREAD

**Issue by seeledu** [ymcui/Chinese-BERT-wwm#83]
RoBERTa-wwm-ext, Chinese 的pytorch 讯飞云下载链接失效了。

**Comment by ymcui** [comment]
我这边可以下载，麻烦贴下你用的哪个链接？

**Comment by ymcui** [comment]
https://pan.iflytek.com/link/92ADD2C34C91F3B44E0EC97F101F89D8
PyTorch（密码waV5）

**Comment by seeledu** [comment]
刚才获取到的链接是这个：
https://pan.iflytek.com/link/2F25AD577CC47EA9CCFC3A038AF29429
现在我也能点开了，谢谢。
