### ISSUE TITLE
couldn't  load the model RoBERTa-wwm-ext-large

### ISSUE THREAD

**Issue by lanmingxiang** [ymcui/Chinese-BERT-wwm#84]
Why I couldn't use  bert-serving-start load the model RoBERTa-wwm-ext-large? Sometimes Python stops running

**Comment by ymcui** [comment]
I am not familiar with bert-serving-start, so I cannot help you with this issue.
RoBERTa-wwm-ext-large should be used in the same way as BERT-large.

**Comment by ymcui** [comment]
Reopen if necessary.
