### ISSUE TITLE
相似度

### ISSUE THREAD

**Issue by lanmingxiang** [ymcui/Chinese-BERT-wwm#88]
如何利用模型获得文本之间的相似度？或者是否有利用Bert做文本相似度和其他方法做文本相似度比较的文献推荐？

**Comment by ymcui** [comment]
相似度这个概念很广，而且相似度计算与是否用BERT表示（还是传统词向量）没有必然联系。
比如预测两个句子是否构成问答对、两个句子是否是蕴含关系等等。
BERT只是文本表示生成器，生成表示后如何去度量相似度需要自行定义。

**Comment by lanmingxiang** [comment]
因为要根据上下文语义做相似度的话Bert比较好，传统的词向量有一定的局限性

**Comment by ymcui** [comment]
这是两回事。BERT只是文本信息更丰富的词向量。至于后面怎么度量相似度，你可以直接拿BERT输出计算cosine，也可以用有标注数据自己设计一个相似度计算的网络。

**Comment by lanmingxiang** [comment]
直接拿bert输出计算cosine是不准确的，不同词不同句子之间没有什么差异，这样只能比较与谁更相似

**Comment by ymcui** [comment]
所以说你可以按照自己的想法设计一个简单的相似度度量的网络，并用已标注的数据去训练。
由于你的这个话题是BERT通用问题，本issue关闭。
建议你去搜索利用神经网络计算文本相似度相关文献。
