### ISSUE TITLE
tokenize后的tokens需要自己加[CLS]和[SEP]吗？

### ISSUE THREAD

**Issue by ParadoxZW** [ymcui/Chinese-BERT-wwm#89]
我在用hugging-face的transformers代码和你们的预训练模型finetune一个nlp任务
然后在模型使用上我有一些问题（主要是不太熟悉transformer的代码，代码量太大，实在没有精力通读orz）：
1. tokenizer.tokenize()后得到的tokens列表需要自己在前后加上[CLS]和[SEP]吗？
2. convert_tokens_to_ids()后得到的ids需要自己padding 0吗？我看预训练的时候应该是固定的512的tokens列表长度，是不是我finetune的时候也要padding到512的长度，还是说可以自己定，比如都padding到100？

**Comment by ymcui** [comment]
1. 是的，具体处理你可以参考官方run_classifier.py：https://github.com/google-research/bert/blob/master/run_classifier.py#L426
2. 是需要padding的，建议同看这部分处理代码

run_classifier.py已经是比较简单的一个下游任务实现了，建议自己再下工夫好好读一下。
