### ISSUE TITLE
cmrc 2108数据集中的问题

### ISSUE THREAD

**Issue by ak47-1234** [ymcui/Chinese-BERT-wwm#9]
1.DRCD是不是用cmrc 2018的评估脚本 (https://github.com/ymcui/cmrc2018/blob/master/data/cmrc2018_evaluate.py) 进行评估的？

**Comment by ymcui** [comment]
1. 请参看：https://github.com/ymcui/CMRC2018-DRCD-BERT
2. 由于DRCD没有官方评测脚本，我们使用的是cmrc2018_evaluate.py。
