### ISSUE TITLE
关于pipeline

### ISSUE THREAD

**Issue by guofei1989** [ymcui/Chinese-BERT-wwm#91]
纯新人，想问个问题。新版本的Transformer中提供了pipeline接口，可快速将模型应用于"feature-extraction"、"sentiment-analysis"、"ner"、"question-answering"和"fill-mask"等任务。我尝试了在pipeline中直接使用Chinese-BERT-wwm，发现报错，请问是没有提供这项功能吗？

**Comment by ymcui** [comment]
模型结构上与谷歌原版BERT没有差别。建议你在原版的中文BERT-base上进行尝试，如果也报错的话就说明不是我们模型的问题。

**Comment by ymcui** [comment]
如有其他问题可以随时reopen
