### ISSUE TITLE
想请问怎么把这个模型放到TFBertModel中，可否提供模型的h5文件？

### ISSUE THREAD

**Issue by JOHNYXUU** [ymcui/Chinese-BERT-wwm#92]

**Comment by ymcui** [comment]
如果你说的是在TF2.0下使用，你可以使用huggingface提供的工具把pytorch权重转换为tf2，还请自行进行转换。
https://github.com/huggingface/transformers/blob/7046de29919169096eded274010d885ae7a89a76/src/transformers/convert_pytorch_checkpoint_to_tf2.py

**Comment by JOHNYXUU** [comment]
谢谢

**Comment by policeme** [comment]
是否支持1.几使用transformers调用模型
