### ISSUE TITLE
请问词表文件中为什么汉字既有加双##的，也有不加的？

### ISSUE THREAD

**Issue by helloworld729** [ymcui/Chinese-BERT-wwm#96]

**Comment by ymcui** [comment]
正常情况下中文用WordPiece分词是不会出现##的。至于谷歌原版词表为什么包含##，这个无从得知。可能是因为编码等问题导致的。
至于你在另外一个帖子里的问题，我们给中文加##符号只用于识别分词（是一种中间保存形式），最终并不会用到。

**Comment by helloworld729** [comment]
谢谢回复，我能理解您对##的用法，确实不能理解这个词表，而且我下载的模型是768维度的，我刚才debug了一下，发现词向量的矩阵正是21128*768，21128就是词表的长度，也就是说所有的token都是有自己的向量的，我推测应该不是编码的问题，以“中”，“##中”为例，他们分别对应不同的向量。所以我推测在实际预训练的时候也使用了加##的汉字的。而且对中文直接调用worldpiece是可以分词出##的，作者可以自己试一下。
例如：
```python
tokenizer = BertTokenizer.from_pretrained('chinese_roberta/vocab.txt')
tokenizer.wordpiece_tokenizer.tokenize("哈尔滨")
['哈', '##尔', '##滨']
```

**Comment by ymcui** [comment]
当然，带不带##显然是两个不同的token，这一点毋庸置疑。
至于为什么有些字有##，有些没有，这取决于WordPiece tokenizer内部的分词机制，常规来说中文会按char来分割。
至于谷歌预训练出来的词表为什么有##，这个无从得知。
如果感兴趣的话，你可以用自己的语料重新训练一个WordPiece分词模型，然后测试一下是否还是包含##符号。

**Comment by helloworld729** [comment]
谢谢回复。
